# Generated by Django 4.2.30 on 2026-07-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_key', models.CharField(max_length=160, verbose_name='题目标识')),
                ('done', models.BooleanField(default=False, verbose_name='已做')),
                ('wrong', models.BooleanField(default=False, verbose_name='做错')),
                ('favorite', models.BooleanField(default=False, verbose_name='已收藏')),
                ('in_wrong_book', models.BooleanField(default=False, verbose_name='在错题本')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='题目标题')),
                ('section_slug', models.SlugField(blank=True, max_length=100, verbose_name='所属小节标识')),
                ('section_title', models.CharField(blank=True, max_length=120, verbose_name='所属小节标题')),
                ('course_slug', models.SlugField(blank=True, max_length=64, verbose_name='所属课程标识')),
                ('course_title', models.CharField(blank=True, max_length=120, verbose_name='所属课程名称')),
                ('problem_type', models.CharField(blank=True, max_length=32, verbose_name='题型')),
                ('difficulty', models.CharField(blank=True, max_length=32, verbose_name='难度')),
                ('knowledge', models.JSONField(blank=True, default=list, verbose_name='知识点')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '做题记录',
                'verbose_name_plural': '做题记录',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='小节标识')),
                ('kind', models.CharField(choices=[('knowledge', '知识库'), ('exercise', '习题库')], default='knowledge', max_length=16, verbose_name='类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='已收藏')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最近学习时间')),
                ('favorited_at', models.DateTimeField(blank=True, null=True, verbose_name='收藏时间')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='小节标题')),
                ('course_slug', models.SlugField(blank=True, max_length=64, verbose_name='所属课程标识')),
                ('course_title', models.CharField(blank=True, max_length=120, verbose_name='所属课程名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '小节学习记录',
                'verbose_name_plural': '小节学习记录',
                'ordering': ['-last_read_at', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_favorite'], name='progress_se_user_id_a275ca_idx'), models.Index(fields=['user', 'last_read_at'], name='progress_se_user_id_e39e9f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sectionrecord',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='uniq_user_section'),
        ),
        migrations.AddIndex(
            model_name='problemrecord',
            index=models.Index(fields=['user', 'in_wrong_book'], name='progress_pr_user_id_ba9b47_idx'),
        ),
        migrations.AddIndex(
            model_name='problemrecord',
            index=models.Index(fields=['user', 'favorite'], name='progress_pr_user_id_cc1570_idx'),
        ),
        migrations.AddConstraint(
            model_name='problemrecord',
            constraint=models.UniqueConstraint(fields=('user', 'problem_key'), name='uniq_user_problem'),
        ),
    ]
