# Generated by Django 4.2.30 on 2026-07-09 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('knowledge', '知识库'), ('exercise', '习题库')], default='knowledge', max_length=16, verbose_name='类型')),
                ('title', models.CharField(max_length=100, verbose_name='章节名称')),
                ('count_label', models.CharField(blank=True, help_text='仅习题库用，例如“86 题”，知识库留空即可', max_length=50, verbose_name='题量说明')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否上线')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '章',
                'verbose_name_plural': '章',
                'ordering': ['course_id', 'kind', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='用于接口地址，例如 calculus', max_length=64, unique=True, verbose_name='课程标识')),
                ('title', models.CharField(max_length=100, verbose_name='课程名称')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('audience', models.CharField(blank=True, max_length=200, verbose_name='适合人群')),
                ('description', models.TextField(blank=True, verbose_name='课程简介')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_published', models.BooleanField(default=True, help_text='关闭后前台看不到这门课', verbose_name='是否上线')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='全站唯一，建议加课程前缀，例如 calculus-limits-sequence', max_length=100, unique=True, verbose_name='小节标识')),
                ('title', models.CharField(max_length=100, verbose_name='小节标题')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='一句话简介')),
                ('access', models.CharField(choices=[('free', '免费'), ('member', '会员')], default='free', max_length=16, verbose_name='访问权限')),
                ('content', models.TextField(blank=True, help_text='用 @chapter/@section/@text/@def/@problem/@solution 等指令写讲义或题目，写法见 TEMPLATE_GUIDE.md', verbose_name='正文（模板指令）')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否上线')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '小节',
                'verbose_name_plural': '小节',
                'ordering': ['chapter_id', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.course', verbose_name='所属课程'),
        ),
    ]
