# Generated by Django 4.2.30 on 2026-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, help_text='用 @chapter/@section/@text/@def/@problem/@solution 等指令写讲义或题目，写法见 docs/TEMPLATE_GUIDE.md', verbose_name='正文（模板指令）'),
        ),
    ]
